server:
  port: 59020

spring:
  jwt:
    # 인증키
    token-signing-key: ZGV2Lm93bmVybWluZC5naWZ0Lmp3dA==
    # 발급자
    token-issuer: miv
    # Access Token 만료시간 10 분
    token-expiration-time: 525600
    # Refresh Token 만료시간 하루:1440, 일주일:10080, 한달:43200, 1년:525600
    refresh-token-expiration-time: 10080

  # ===============================
  # Spring Jpa Config
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    # database-platform: org.mariadb.jdbc.Driver
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  # ===============================
  # Spring Database Config
  # ===============================
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/app_server?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8
    username: miv
    password: 1234